#title in header
title: "Hi Folks."

#main info
#owner
owner: "I am Adi Sakti Jrs"
info: "A student and web developer from Indonesia ğŸ‡®ğŸ‡©"
#description
desc: "This is Minima, an undoubtedly simple and lightweight dark/light mode theme for Hexo. I created this from scratch using Skeleton CSS boilerplate. It only uses CSS and Vanilla JS, without using unnecessary third-party 'render-blocking' libraries! ğŸ˜"

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# social profile at the footer/bottom
place: https://www.google.com/search?q=kendal+jawa+tengah
github: https://github.com/adisaktijrs
instagram: https://www.instagram.com/adisaktijrs/
twitter: https://twitter.com/adisaktijrs

# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.png

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: https-adisaktijrs-github-io
