# Title in header
title: "é›ªã€ç„¡éŸ³ã€çª“è¾ºã«ã¦ã€‚"

# INFO
# Owner info
owner: ""
info: "æš–ã‹ã„æ—¥å·®ã—ã‚’å—ã‘ã¦ã€€æ¡ƒè‰²ã®èŠ±ã³ã‚‰ãŒã€€é£›ã³"
# Description, will be displayed at second line
desc: "èˆã„æ•£ã‚‹é›ªã®å­£ç¯€ãŒã¾ãŸã€€çµ‚ã‚ã‚Šã‚’å‘Šã’ã‚‹ã€€å¦–ç²¾ã‚ˆã€€ãµã‚‰ãµã‚‰ã‚Šã€€ç¾ã‚Œã¦ãã‚‹"

# Main page top menu bar
menu:
  Archives: /archives
  Playground: ../play
  Links: /external
  PGP Key: https://pgp.yukimuon.com
  .ME: /about

# Index/main page max show posts (in number)
max_post: 4

# Colors for links and top nanobar, use hex color without #
tcolor: ff6f61
ncolor: ffb7c5

# Social profile at the footer/bottom, default close
profile: false
place: 
github: 
instagram: 
twitter: 
date: false

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dard: ğŸŒ•

# Favicon
favicon: /images/favicon.png

article:
  thumbnail: false

# DISQUS comments (sign up to Disqus to get disqus_shortname). default close
disqus_enabled: false
disqus_shortname:
