# Title in header
title: "Hexo theme Minima!"

# INFO
# Owner info
owner: "I am Adi Sakti Jrs!"
info: "A student and web developer from Indonesia ğŸ‡®ğŸ‡©"
# Description, will be displayed at second line
desc: "This is Minima, a great minimal style theme for Hexo!"

# Main page top menu bar
menu:
  Archives: /archives
  About: /about

# Index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE 
# Nanobar color
ncolor: FF5869
lighttheme_color: ffdee4

# Social profile at the footer/bottom, default close
footer: true
place: 
github: 
instagram: 
twitter: 

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dard: ğŸŒ•

# Favicon
favicon: /images/favicon.png

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname). default close
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
