# Title in header
<<<<<<< HEAD
title: "Èõ™„ÄÅÁÑ°Èü≥„ÄÅÁ™ìËæ∫„Å´„Å¶„ÄÇ"

# INFO
# Owner info
owner: ""
info: "Êöñ„Åã„ÅÑÊó•Â∑Æ„Åó„ÇíÂèó„Åë„Å¶„ÄÄÊ°ÉËâ≤„ÅÆËä±„Å≥„Çâ„Åå„ÄÄÈ£õ„Å≥"
# Description, will be displayed at second line
desc: "Ëàû„ÅÑÊï£„ÇãÈõ™„ÅÆÂ≠£ÁØÄ„Åå„Åæ„Åü„ÄÄÁµÇ„Çè„Çä„ÇíÂëä„Åí„Çã„ÄÄÂ¶ñÁ≤æ„Çà„ÄÄ„Åµ„Çâ„Åµ„Çâ„Çä„ÄÄÁèæ„Çå„Å¶„Åè„Çã"
=======
title: "Hello! This is Hexo theme Minima!"

# INFO
# Owner info
owner: "I am Adi Sakti Jrs!"
info: "A student and web developer from Indonesia üáÆüá©"
# Description, will be displayed at second line
desc: "This is Minima, a great minimal style theme for Hexo!"
>>>>>>> 64d9df955bb98bece9c383f3724b2280dcc164fd

# Main page top menu bar
menu:
  Archives: /archives
<<<<<<< HEAD
  Playground: ../play
  Links: /external
  PGP Key: https://pgp.yukimuon.com
  .ME: /about
=======
  About: /about
>>>>>>> 64d9df955bb98bece9c383f3724b2280dcc164fd

# Index/main page max show posts (in number)
max_post: 4

# Colors for links and top nanobar, use hex color without #
<<<<<<< HEAD
tcolor: ff6f61
ncolor: ffb7c5
=======
tcolor: 0FA0CE
ncolor: FF5869
>>>>>>> 64d9df955bb98bece9c383f3724b2280dcc164fd

# Social profile at the footer/bottom, default close
profile: false
place: 
github: 
instagram: 
twitter: 
date: false

# Misc
nanobar: /js/nanobar.min.js
switch_light: ‚òÄÔ∏è
switch_dard: üåï

# Favicon
favicon: /images/favicon.png

article:
  thumbnail: false

# DISQUS comments (sign up to Disqus to get disqus_shortname). default close
disqus_enabled: false
disqus_shortname:
